#!/bin/sh
#
# Copyright (C) 2011 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

if [ -e /dev/hvc0 -a -f /target/etc/inittab ]; then  # xen, using inittab
  if ! grep -q ^hvc0: /target/etc/inittab; then
    echo "hvc0:2345:respawn:/sbin/getty 38400 hvc0" >> /target/etc/inittab
  fi
fi
